### ISSUE TITLE
How to use wandb

### ISSUE THREAD

**Issue by JDesperado** [Cognitive-AI-Systems/learn-to-follow#2]
Dear Author, I would like to express my gratitude for your contributions to this project.  As a first-year graduate student, I have recently attempted to run your project.  Could you please advise me on how to visualize the training process?  Should I add `wandb.log` into `main.py`?  I appreciate your assistance and look forward to your response.

**Comment by Tviskaron** [comment]
Hi! Wandb is enabled by default, but it is disabled for runs of main.py without any arguments. This mode acts as a debugging mode to allow easy testing of the training process without logging any data. 

If you want to train a model (e.g., FollowerLite), you can provide the required arguments as mentioned in the README file.

To train **FollowerLite** from scratch, use the following command:
```bash
python3 main.py  --actor_critic_share_weights=True --batch_size=16384 --env=PogemaMazes-v0 --exploration_loss_coeff=0.0156 --extra_fc_layers=0 --gamma=0.9716 --hidden_size=16 --intrinsic_target_reward=0.01 --learning_rate=0.00013 --lr_schedule=kl_adaptive_minibatch --network_input_radius=3 --num_filters=8 --num_res_blocks=1 --num_workers=4 --optimizer=adam --ppo_clip_ratio=0.2     --train_for_env_steps=20000000 --use_rnn=False
```

More specifically, wandb logging is skipped if the --train_for_env_steps parameter is set to 1000000 (1M steps). To enable wandb logging, you can change this parameter:
```
command: python3 main.py --train_for_env_steps=1000042
```

**Comment by JDesperado** [comment]
Thanks for your detailed reply. After listening to your suggestions, I successfully obtained the visualization process. As you said, setting the --train_for_env_steps parameter to 1000000 skips logging, which I set to 1000000 in the beginning. Besides, i would like to know the difference between the Follower method and the FollowerLite method.

**Comment by Tviskaron** [comment]
FollowerLite is a lightweight version of Follower, with no RNN heads and fewer parameters. For more detailed information, please refer to Table 1 in the appendix of https://arxiv.org/abs/2310.01207

**Comment by JDesperado** [comment]
I see. I will read your article carefully. I wish you all the best!

**Comment by JDesperado** [comment]
Sorry to bother you again, but for displaying the generated.SVG file, can you make each agent stop once it reaches the target point? For example, each agent only performs path planning once and then stops, and then waits for other agents to arrive at the target point successively. If so, how do I modify the code?

**Comment by Tviskaron** [comment]
The issue is not with the generated SVG but with the definition of the problem. In the Learn-to-Follow paper, we consider the lifelong case, where the targets change immediately after they are reached. POGEMA supports different modes, and the one you mentioned is the classical MAPF. This can be configured by setting on_target='nothing'. However, since Follower solves the lifelong MAPF case, in MAPF mode the performance will be extremely low. 

For MAPF scenario, I suggest looking into our recent preprint: https://arxiv.org/abs/2409.00134, and the corresponding open-source code: https://github.com/Cognitive-AI-Systems/MAPF-GPT

**Comment by JDesperado** [comment]
I understand. Thank you once again for your help. Your work is excellent. I will continue running MAPF-GPT.
