### ISSUE TITLE
how to use learn-to-follow-raw-data

### ISSUE THREAD

**Issue by JDesperado** [Cognitive-AI-Systems/learn-to-follow#3]
As shown, I try to use eval.py. I change the BASE_PATH to learn-to-follow-raw-data, And set it to ToolboxRegistry.register_env('WarehouseWFI-v0', create_env_base, Environment). But what should I do if the following error occurs.Looking forward to your reply!
![2024-09-12 08-52-47 的屏幕截图](https://github.com/user-attachments/assets/4dfe6b1d-1dc1-46ac-95fd-6743648a2c0b)

![2024-09-12 08-35-55 的屏幕截图](https://github.com/user-attachments/assets/43f3257f-2695-48e2-8248-734404d9ddcf)
![2024-09-12 08-36-12 的屏幕截图](https://github.com/user-attachments/assets/59d6c60a-aa1f-4ba8-9074-39bee87d5be5)

**Comment by Tviskaron** [comment]
First, I have observed this error with certain versions of gymnasium. Could you please share the versions of pogema, pogema-toolbox, and gymnasium you are using (from the output of pip freeze)? If you can successfully run `eval.py` just ignore my concern. 

Secondly, you don’t need to modify or copy anything from the eval.py script, especially the environment name – always leave it as `Pogema-v0`. To run experiments on the warehouse environment, simply run `eval.py` with:

```python
folder_names = [
    '05-warehouse',
]
```
Then, adjust 05-warehouse.yaml in that folder. This will be enough to reproduce the ablation study experiment.

**The raw data is provided as is and is not directly linked to the code, but represents the results of the experiment, which were used to generate the plots and tables in the paper.**

For the Episode Length experiment in Figure 6, we used a custom script to save the results at each step using an additional wrapper. The plot was generated with another custom script. We don’t plan to include this code in the main repository since it requires extra setup steps and would unnecessarily complicate the process (e.g., by adding extra, irrelevant data to the main experiments).

Here’s the code for the wrapper:
```python
class EveryStepThroughputMetric(AbstractMetric):

    def __init__(self, env, ):
        super().__init__(env)
        self._solved_instances = 0
        self._intermediate_throughput = [0]

    def _compute_stats(self, step, is_on_goal, finished):
        for agent_idx, on_goal in enumerate(is_on_goal):
            if on_goal:
                self._solved_instances += 1
        self._intermediate_throughput.append(self._solved_instances / (step + 1))
        if finished:
            result = {'every_step_throughput': self._intermediate_throughput}
            self._solved_instances = 0
            self._intermediate_throughput = [0]
            return result
```

If you need further assistance, feel free to ask!

**Comment by JDesperado** [comment]
First, I really appreciate your detailed response. I'm using versions gymnasium==0.28.1, pogema==1.3.0, and pogema-toolbox==0.1.0, and I can run `eval.py` and successfully plot graphs from the experiments folder.

Secondly, if I want to use `eval.py` and set `folder_names = ['05-warehouse']`, how should I adjust the `05-warehouse.yaml`? For example, if I want to change the `map_name`, or if I want to test other algorithm variants not listed. By the way, where can I get variants of these algorithms, and what are the other available algorithm variants? Also, for new JSON files, can I modify them based on this structure? How are the JSON files generated? Are they generated through training `follower` or `follower lite`?"

**Comment by Tviskaron** [comment]
If you want to change the `map_name`, you can directly modify it in yaml file. We can replace `map_name: wfi_warehouse` to any available map_name, which can be found in this [file](https://github.com/Cognitive-AI-Systems/learn-to-follow/blob/main/env/test-maps.yaml), or a to several map names using `grid_search` option. 

JSON files are generated during the evolution process and are used to store the results of the algorithms. During training, we only support logging through wandb. 

If you want to modify an algorithm or its parameters, you can find examples in the [Pogema Toolbox repo](https://github.com/Cognitive-AI-Systems/pogema-toolbox). Specifically for the Follower algorithm, you can find an example of running the algorithm with different parameters in the ablation experiment on the warehouse map: 

```yaml
algorithms:
  Follower:
    name: Follower
    num_process: 4
    parallel_backend: 'balanced_dask'


  No dynamic cost:
    name: Follower
    num_process: 4
    parallel_backend: 'balanced_dask'
    
    override_config:
      preprocessing:
        use_dynamic_cost: False

  No static cost:
    name: Follower
    num_process: 4
    parallel_backend: 'balanced_dask'
    
    override_config:
      preprocessing:
        use_static_cost: False
```

**Comment by JDesperado** [comment]
I'm sorry, but I still don't understand how the JSON files are generated and applied in the ablation experiments. Could you please explain this in more detail?

Additionally, regarding algorithm variants, I have successfully run the ablation experiments from the example. Besides "No dynamic cost" and "No static cost," are there any additional variants available to choose from? Or, if I want to use other variants like "No dynamic cost and No static cost," do I need to customize them myself? In this process, are JSON files required?

**Comment by Tviskaron** [comment]
Let’s take this ablation experiment as an example. When you run `eval.py` for the warehouse experiment, there are three types of Follower algorithms: `Follower`, `No dynamic cost`, and `No static cost`. These names can vary, as they just need to distinguish between algorithms (you even can rename them if needed). The differences lie in the parameters, such as setting `use_static_cost: False`. So, this is how the algorithms can be adjusted, and JSON files are not required for these modifications.

Afterward, for each algorithm and each map type defined at the top of the YAML script, the pogema-toolbox runs evaluations. The raw results of these evaluations are stored in JSON files. For example, the results for the `No dynamic cost` will be saved in a file named `No dynamic cost.json`, in the experiment folder. These results can then be used to generate plots without needing to rerun the experiment (it's a form of raw results data).

**Comment by JDesperado** [comment]
I have understood your explanation. I noticed the reset_dynamic_cost parameter. Could you please explain this parameter? Additionally, in the same YAML file, can reset_dynamic_cost, use_dynamic_cost, and use_static_cost all be set to false at the same time? What is the difference between them? Besides that, are there any other algorithms and variants?
![2024-09-14 15-12-22 的屏幕截图](https://github.com/user-attachments/assets/5c85edc5-b5e0-43c4-8d09-01957c9db533)

**Comment by Tviskaron** [comment]
These arguments implement the functionality described in the paper, namely Precalculated Cost and Cost Accumulation, which are enabled by default. The reset_dynamic_cost option, which is also enabled by default, is used to prevent the negative impact of over-accumulating dynamic penalties (also, as mentioned in the paper). 

There are also some learning-specific parameters, but they should not affect inference. The repository provides only Follower and FollowerLite algorithms🙂

**Comment by JDesperado** [comment]
Got it, I understand now. Thank you for your patient response!
